[book]
title = "Terraria World Library"
authors = ["osbm"]
description = "A Rust library for reading and writing Terraria world files."
language = "en"

[output.html]
git-repository-url = "https://github.com/osbm/terraria-world-rs"
edit-url-template = "https://github.com/osbm/terraria-world-rs/edit/main/docs/{path}"
