name: build and test rust library

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  nix-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Run nix build -L
        run: nix build -L 
